language: php

sudo: false

php:
- 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files

install: travis_retry composer update $COMPOSER_FLAGS

script: ./vendor/bin/simple-phpunit
